### PR TITLE
weak articulation

### PR DESCRIPTION
**Pull request by LinguList**
@cormacanderson, I had to fix some lines, but it works now, and this change does not require to touch the code, so it integrates nicely.

### CODE REVIEW

**Comment by LinguList** [comment]
This PR goes close to the actual release. What is left to do is creating CLDF data, and to double check. In my opinoin, all tests run, and there are no problems. @xrotwang and @chrzyki, would you like to double check and make the release 3.3?

**Comment by chrzyki** [comment]
Yes, I can have a look as well. I'll test on this branch, `release-3.3`, correct?

**Comment by LinguList** [comment]
Yes, that would be my suggestion :-)

**Comment by chrzyki** [comment]
Add `weak articulation` to features here: https://github.com/cldf-clts/clts/pull/145/commits/463c13b752347e8c376e79dd818413b0057668ba

Apart from that, everything looks fine from my end. The only other thing before releasing would be to update the metadata: https://github.com/cldf-clts/clts/blob/release-3.3/metadata.json to 2024?

**Comment by LinguList** [comment]
Yes, metadata should be updated. Thanks! I would then be fine in merging and proceeding with the release.

**Comment by xrotwang** [comment]
I guess release is something I'd do, then, since it also involves updating the clld app.

**Comment by LinguList** [comment]
Yes, thanks @xrotwang !

**Comment by chrzyki** [comment]
Thanks! If there is anything else I can do to help with the release (here or with the clld app) please let me know.

**Comment by xrotwang** [comment]
Where does "3.3" come from as release tag? I'd tag this as "2.3.0".

**Comment by LinguList** [comment]
You are right. I got confused.

**Review by xrotwang — APPROVED** [review]

**Pull request merged**
