### PR TITLE
add clusters and new features

### PR DESCRIPTION
**Pull request by LinguList**
PR adds clusters as a new type of sounds, and features for double-articulation.

### CODE REVIEW

**Comment by LinguList** [comment]
@cormacanderson, maybe you can also check the new sounds?

**Review by tresoldi — APPROVED** [review]

**Comment by tresoldi** [comment]
Sorry, I have merged it. Let me know if I should revert.

**Comment by cormacanderson** [comment]
Good are the following:
bilabial-and-alveolar
alveolar-and-bilabial
velar-and-bilabial

Unattested as far as my reading of the literature goes are:
bilabial-and-velar
velar-and-alveolar
alveolar-and-velar

Optionally:
bilabial-and-palatal (replacing labio-palatal)
velar-and-bilabial (replacing labio-velar)

We also would need:
uvular-and-labial
uvular-and-epiglottal

And the dental rather than alveolar ones:
bilabial-and-dental
dental-and-bilabial

**Comment by LinguList** [comment]
The unattested ones come from Mielke's P-Base! they are all attested in
at least one dataset...

**Comment by cormacanderson** [comment]
Okay then, I look forward to chasing them up :P

**Pull request merged**
