### PR TITLE
updated and walked through release instructions

### PR DESCRIPTION
**Pull request by xrotwang**
Note that `clts make_app` and `clts dump` are not idempotent! I think this should be fixed to make sure we get inspectable, meaningful diffs for the derived data as well.

### CODE REVIEW

**Comment by xrotwang** [comment]
@LinguList I think we'd need a better sort key here: https://github.com/cldf-clts/pyclts/blob/64e68197b23c2dfdaf7b7bdff67311baadaf9e20/src/pyclts/commands/dump.py#L52 - resulting in a complete order.

**Comment by xrotwang** [comment]
Took a bit more, see https://github.com/cldf-clts/pyclts/commit/34aec11bfbfddab644ec2d47114a5fe801812dd9
I'd still say, we release pyclts 3.0.1 first and then this repos?

**Comment by LinguList** [comment]
sorry, my notifications were not working, so I receive this only now, will check immediately.

**Comment by LinguList** [comment]
>  I'd still say, we release pyclts 3.0.1 first and then this repos?

Yes, first pyclts and then this one.

**Comment by LinguList** [comment]
I mean, the good thing is that this was caught now. We need to have a good and reliable workflow for CLTS, as this is probably not the last release we make.

**Pull request merged**
